### ISSUE TITLE
Info on Arch Linux

### ISSUE THREAD

**Issue by Ingo-Albrecht** [splondike/wayland-accessibility-notes#2]
Hi,

I saw your notes on a11y yesterday and write to give some info for the Arch Linux part.[1]

You probably know Arch is pretty minimalistic, with its main install procedure being based on a CLI command guide and not installing any graphical environment by default. A very dedicated person developed an Arch installation medium derivate including espeak and braille, named TalkingArch. Some time later Arch developers took up the task to include the TalkingArch work into the regular Arch installation medium. This project ended with the release announcement.[2] Since then espeak/braille support is regularly maintained by the developers along with the rest of the installation medium.

As mentioned every regular Arch installation ends with no WM/DE installed. It's up to the user to decide for one (or two) to install and the upstream WM/DE defaults will usually carry over. For example, if you choose GDM/GNOME, it will default to wayland when enabling the default gdm.service. This one example because it requires a fair bit of reading to set up a full desktop.

The links:

[1] Your note section I refer to: https://github.com/splondike/wayland-accessibility-notes/blob/main/communities.md#arch-linux
[2] Arch release announcement: https://archlinux.org/news/accessible-installation-medium/
[3] ArchWiki category with related articles: https://wiki.archlinux.org/title/Category:Accessibility
[4] ArchWiki List of applications category: https://wiki.archlinux.org/title/List_of_applications/Other#Accessibility

I hope there is something useful for you to cherry-pick among this, I surely found your public notes extremely informative and useful.

**Comment by splondike** [comment]
Thanks for the info, I've updated the section on Arch to mention the espeak/braille support. Glad you've found the notes helpful :).
